### ISSUE TITLE
使用4卡跑一直报错

### ISSUE THREAD

**Issue by ghost** [Scottdyt/HAKG#5]
我使用的是Dataparallel，一直出现这样的问题，请问我是哪里出错了
![image](https://user-images.githubusercontent.com/102452987/191643801-58366911-3097-4d14-82b0-cc5c02b0b382.png)

**Comment by yuntaod** [comment]
It seems your tensors are located in different GPU, thus cannot be directly computed. 
We only test our model in a single GPU, so it may need some modification for multi-GPU setting.
