### ISSUE TITLE
code inconsistent with your paper

### ISSUE THREAD

**Issue by Tuo97** [Scottdyt/HAKG#6]
Why is the model code inconsistent with your paper description?

**Comment by yuntaod** [comment]
Please indicate the inconsistence so we can enhance the public code together :)

**Comment by Tuo97** [comment]
1) In your paper Eq.14 aggregates neighbors in Euclidean space and maps them back to hyperbolic space. In the code, aggregation is only performed in Euclidean space.

2) According to the description in your paper, Eq 15  should be sum pooling in hyperbolic space. While the code， embedding is summed in Euclidean space.

3) According to the code, it seems that you are only in Eq 6 (KG) uses hyperbolic space exponential mapping, while the CF part only uses the calculation of Euclidean space. Does the innovation of the paper only focus on the KG part and not the CF part?

**Comment by yuntaod** [comment]
Thanks for pointing out!
In fact, the choose of whether mapping between hyperbolic space and Euclidean space depends on the optimization method. In our implementation, we use Euclidean optimization method (a.k.a. Adam, as described in Section 4.1.1) for simplicity. Thus, we only need to make sure the critical hyperbolic operations are performed in Hyperbolic space (like Hyerbolic Cone), and optimize the embeddings in Euclidean space. 
It should be mentioned that HAKG conducts all GNN operations in Euclidean space (no matter first map from Hyerpbolic space, or directly sum pooling in Euclidean space). For example, Eq. 15 first maps the embedding to Euclidean space and sums neighboring nodes, not directly sums in hyerbolic space. 
It is also interesting and feasible to optimize all parameters in hyperbolic space, however, it would need a lot more GPU memory and slow down the training, thus we choose a simple alternative. The innovation of HAKG is not embedding in hyperbolic space, but the hierarchical relations and information gate mechanism for comprehensive representation learning.

**Comment by Tuo97** [comment]
Thank you very much for your reply！
