### ISSUE TITLE
关于 Yelp2018 dataset

### ISSUE THREAD

**Issue by LuckyDL21** [Scottdyt/HAKG#8]
你好，关于hakg的论文看完了。
为了直接运行代码，
我想获得Yelp 2018 raw dataset，但因为我是外国人，所以没能加入qq网站，无法下载review数据。 如果不失礼的话，希望通过谷歌驱动链接共享数据。

谢谢。

**Comment by yuntaod** [comment]
Hi, 

Thanks for your attention! We have added the other two datasets for reference, and you can find them [here](https://github.com/zealscott/HAKG/tree/main/data) now.

Hope it helps, cheers :)

**Comment by LuckyDL21** [comment]
Hello author, I am a researcher who left an issue to HAKG GitHub about the last YELP2018 dataset. It's just that I'm interested in the cold start problem, so I'm turning the code for the metakg paper code. By the way, the raw data (https://www.yelp.com/dataset)) I have is different from the Yelp 2018 dataset, so if I run construction data.py, the data seems to be processed strangely.

I wonder if you could share the Yelp 2018 review data and business data by email. 

Thank you for always doing good research.

Thank you :)
 
 
 
 
 
 
 
-----Original Message-----
