### ISSUE TITLE
maybe a bug?

### ISSUE THREAD

**Issue by lannester666** [Scottdyt/HAKG#9]
when I run the code,I find that I have to change 
graph_tensor = torch.tensor(list(graph.edges))  to
graph_tensor = torch.tensor(list(graph.edges(keys=True)))  in HAKG.py,line224.
Otherwise the keys will not be shown in graph.edges().Maybe it's caused by the version of networkx.Hope this can help those who have the same problem.

**Comment by yuntaod** [comment]
Thanks for your advice. We check our code and it ran smoothly with networkx == 2.5. I added the requirements for reminder.
